on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: read node.js version
        id: nodejs-version
        run: |
          content=`cat ./.nvmrc`
          echo "::set-output name=content::$content"
      - uses: actions/setup-node@v2
        with:
          # See https://github.com/actions/setup-node/issues/32
          node-version: ${{ steps.nodejs-version.outputs.content }}
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
